CREATE TRIGGER log_bruger_changes
AFTER INSERT OR UPDATE OR DELETE
ON bruger
FOR EACH ROW
EXECUTE PROCEDURE log_query();

CREATE TRIGGER log_vagt_changes
AFTER INSERT OR UPDATE OR DELETE
ON vagt
FOR EACH ROW
EXECUTE PROCEDURE log_query();

CREATE TRIGGER log_booking_changes
AFTER INSERT OR UPDATE OR DELETE
ON booking
FOR EACH ROW
EXECUTE PROCEDURE log_query();
